# Generated by Django 4.0.3 on 2022-03-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankieta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odpowiedz',
            options={'verbose_name': 'Odpowiedź', 'verbose_name_plural': 'Odpowiedzi'},
        ),
        migrations.AlterModelOptions(
            name='pytanie',
            options={'verbose_name': 'Pytanie', 'verbose_name_plural': 'Pytania'},
        ),
        migrations.AddField(
            model_name='pytanie',
            name='obraz',
            field=models.CharField(default='brak.jpg', max_length=255),
        ),
    ]
